spring:
  application:
    name: dbdeep-BE
  config:
    import:
      - application-mysql.yml
      - optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    time-zone: Asia/Seoul
  mvc:
    servlet:
      path: /api
  data:
    elasticsearch:
      uris: ${ES_URI}
      repositories:
        bootstrap-mode: lazy
        enabled: true
    redis:
      host: redis
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secretKey: ${JWT_SECRET}

cors:
  allowed-origins:
    - http://localhost:5173
    - https://k12s104.p.ssafy.io
    - https://dbdeep.kr
    - http://k12s104.p.ssafy.io
    - http://dbdeep.kr

firestore:
  credential-location: ${FIRESTORE_CREDENTIAL_LOCATION}