spring:
  application:
    name: dbdeep-BE
  config:
    import:
      - application-mysql.yml
      - optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    time-zone: Asia/Seoul
  mvc:
    servlet:
      path: /api
  data:
    elasticsearch:
      repositories:
        enabled: true
      uris: http://localhost:9200
jwt:
  secretKey: ${JWT_SECRET}

cors:
  allowed-origins:
    - http://localhost:5173
    - https://k12s104.p.ssafy.io
    - https://dbdeep.kr
    - http://k12s104.p.ssafy.io
    - http://dbdeep.kr