server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, Gateway-Service
      routes:
        - id: app-service
          uri: http://dbdeep-app:8080
          predicates:
            - Path=/backend/api/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secretKey: ${JWT_SECRET}